swagger: "2.0"
info:
  title: "User Service API"
  description: "API documentation for the User Service"
  version: "1.0.0"
basePath: "/api/v1"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /register:
    post:
      summary: "User Registration"
      description: "Allows users to register by providing their information."
      parameters:
        - name: body
          in: body
          description: "User registration data"
          required: true
          schema:
            $ref: "#/definitions/UserRegistration"
      responses:
        200:
          description: "User registered successfully"
        400:
          description: "Invalid input data"
        500:
          description: "Internal server error"
  /verify-email:
    post:
      summary: "Email Verification"
      description: "Allows users to verify their email addresses using a verification code sent via email."
      parameters:
        - name: body
          in: body
          description: "Email verification data"
          required: true
          schema:
            $ref: "#/definitions/EmailVerification"
      responses:
        200:
          description: "Email verified successfully"
        400:
          description: "Invalid input data"
        500:
          description: "Internal server error"
  # Add more paths for other APIs here...
definitions:
  UserRegistration:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  EmailVerification:
    type: "object"
    properties:
      email:
        type: "string"
      verification_code:
        type: "string"
