version: '3.8'

services:
  user_service:
    build: .
    image: user_service_image:latest
    container_name: user_service_container
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - user_service_network
    volumes:
      - .:/app
    environment:
      - RUNNING_IN_DOCKER=true
    restart: always

  rabbitmq:
    container_name: user_service_rabbitmq_container
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - 5672
      - 15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user_service_network

networks:
  user_service_network:
    driver: bridge
