version: '3.8'

services:
  user_service:
    build: .
    container_name: user_service_container
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - user_service_network

  rabbitmq:
    container_name: user_service_rabbitmq_container
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - 5672
      - 15672
    networks:
      - user_service_network

networks:
  user_service_network:
    driver: bridge
