# Production Configuration

# HTTP and HTTPS Ports
http_port: 80
https_port: 443

# Host Configuration
host: <production-host>

# JWT Configuration
jwt_secret_key: <jwt-secret-key>
jwt_expiration: <jwt-expiration>
refresh_token_expiration: <refresh-token-expiration>

# RabbitMQ Configuration
rabbitmq:
  username: <rabbitmq-user-name>
  password: <rabbitmq_password>
  host: <rabbitmq-host>
  port: <rabbitmq-port>

# Email Configuration
email:
  provider: "mailjet"  # This can be "mailjet", "sendgrid", etc
  mailjet:
    smtp_server: "in-v3.mailjet.com"
    smtp_port: 587
    smtp_user: "smtp_username"
    smtp_password: "smtp_password"
    sender_email: "mailjet_sender_email@example.com"
    sender_name: "Mailjet Sender"

  sendgrid:
    smtp_server: "smtp.sendgrid.net"
    smtp_port: 587
    smtp_user: "apikey"
    smtp_password: "<sendgrid_api_key>"
    sender_email: "sendgrid_sender_email@example.com"
    sender_name: "Sendgrid Sender"

  generic:
    smtp_server: "smtp.example.com"
    smtp_port: 587
    smtp_user: "smtp_username"
    smtp_password: "smtp_password"
    sender_email: "generic_sender_email@example.com"
    sender_name: "Generic Sender"

  verification_email_expiration: <verification-email-expiration>   # Expiration time for the verification email
  password_reset_email_expiration: <password-reset-email-expiration>  # Expiration time for the password reset email

# SMS Configuration
sms:
  twilio_account_sid: "production_twilio_account_sid"
  twilio_auth_token: "production_twilio_auth_token"
  twilio_phone_number: "+1234567890"

# FCM Device Token
fcm_device_token: "<fcm-device-token>"

# Database Configuration
database:
  sqlite:
    enabled: false  # Disable SQLite for production
    driver: sqlite3
    file: "production.sqlite3"
  postgresql:
    enabled: true  # Enable PostgreSQL for production
    host: "production_postgresql_host"
    port: 5432
    user: "production_postgresql_user"
    password: "production_postgresql_password"
    dbname: "production_postgresql_dbname"
  firebase:
    enabled: true
    api_key: "production_firebase_api_key"
    project_id: "production_firebase_project_id"
    storage_bucket: "production_firebase_storage_bucket"
    auth_domain: "production_firebase_auth_domain"
    database_url: "https://production-firebase-database-url.firebaseio.com"
    service_account_key: '{
      "type": "service_account",
      "project_id": "project_id",
      "private_key_id": "private_key_id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nPrivate_Key\n-----END PRIVATE KEY-----\n",
      "client_email": "client_email",
      "client_id": "client_id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "client_x509_cert_url"
    }'
