definitions:
  models.UserResponse:
    properties:
      message:
        description: Customize the response fields as needed
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the given email and password.
      parameters:
      - description: Email (required)
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password (required)
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: First Name (required)
        in: body
        name: first_name
        schema:
          type: string
      - description: Middle Name (optional)
        in: body
        name: middle_name
        schema:
          type: string
      - description: Last Name (required)
        in: body
        name: last_name
        schema:
          type: string
      - description: Date of Birth (optional) (YYYY-MM-DD)
        in: body
        name: date_of_birth
        schema:
          type: string
      - description: Phone Number (optional)
        in: body
        name: phone_number
        schema:
          type: string
      - description: Address (optional)
        in: body
        name: address
        schema:
          type: string
      - description: Country (optional)
        in: body
        name: country
        schema:
          type: string
      - description: Province (optional)
        in: body
        name: province
        schema:
          type: string
      - description: Avatar URL (optional)
        in: body
        name: avatar_url
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.UserResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.UserResponse'
      summary: Register a new user
swagger: "2.0"
